### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by DQvsRA** [photoshelter/generator-polymer-init-element-scaffold#33]
## Not working
:bug:      (bug)

After scaffold complete, i run "npm start" and that's what i have:

![screenshot from 2017-01-24 22 06 23](https://cloud.githubusercontent.com/assets/442111/22266777/8bcd0082-e281-11e6-8f7a-8d74630c1a07.png)

**Comment by Westbrook** [comment]
@DQvsRA it seems some files are missing from the scaffolded structure. Would you take a minute to supply a little more information about your experience:

What version of the scaffold are you using?
Can you confirm all of the commands you enacted to get to this point?
Did you choose to effect the file structure in anyway before running `npm start`?

Thanks for being interesting in the project. I hope we can get this to a beneficial part of your workflow.

**Comment by caranicas** [comment]
based off that screen shot, it looks like a bug in the 2.0 template not properly copying over the styles or js file.

**Comment by caranicas** [comment]
Yep. There was param missing in a function that I refactored  😵. I fixed it, make sure you update to version `0.2.3` also as a side note 2.0 elements rely on some es6 features. They will run in Chrome Canary, or can be imported into a project that has some transpiling process. 

thanks for catching that bug, if you have any more questions, or ideas for things we could improve please don't hesitate.

**Comment by DQvsRA** [comment]
Now after update i have only this

![screenshot from 2017-01-29 12 27 24](https://cloud.githubusercontent.com/assets/442111/22403648/519ec8dc-e61e-11e6-9403-bdfc7ce2fad2.png)

**Comment by caranicas** [comment]
Can you run a `npm ls -global` for me and double check that you are on version 0.2.3 ?

I am seeing a few things that don't make sense. You picked an internal component, so there isn't a build process, its a more pure template that is meant to be built into an existing app.

**Comment by caranicas** [comment]
Ok I understand your confusion. The yeoman generator talks about doing an install, and you didn't see the node_modules folder and then you ran it yourself and it failed. 

But what i said originally still holds true. If you are building an internal component there is nothing else to install. If you are trying to build a generic component that you want to import then you would pick bower vs internal.

**Comment by DQvsRA** [comment]
Yes, i see there is no package.json
