### ISSUE TITLE
BUG: polymer init element-scaffold 2.0

### ISSUE THREAD

**Issue by oneezy** [photoshelter/generator-polymer-init-element-scaffold#48]
### Description
I'm running into an issue when trying to create a `Polymer 2.0` element. 
I'm able to step through the generator just fine,, 

![image](https://user-images.githubusercontent.com/7369575/27364877-ab19172e-5602-11e7-94f4-60d351ebd437.png)

But when I `npm start` I get the `NOT WORKING ?` text and `Failed to load resource` error,,

![image](https://user-images.githubusercontent.com/7369575/27365149-29bd3884-5604-11e7-8d6b-5414c1149afa.png)

It looks like you've got it generating the old `2.0 preview` code,, but I'm not sure if this is the problem. 
(I thought I remembered this working at a previous version).

-----

Any ideas?

-----

### Environment :globe_with_meridians:

* Version used: **Node 8.0**, **NPM 5.0.3**, **Polymer CLI v1.2.0**, and **Element Scaffold v0.2.5**.
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Win 10 w/ "Bash on Ubuntu on Windows"
* Link to your project:

**Comment by caranicas** [comment]
@oneezy Yeah, we are a little behind in our generator updates. I couldn't say exactly what the issue is. We should be getting to updating the generator to the official 2.0 version in the next few weeks  🤞  as we shift gears. Feel more than free to make the update on your own and send a PR if you can get it working. 👍

**Comment by caranicas** [comment]
Took a look of the weekend, seems like just a few simple changes are needed. If I don't get this out today, then it will be one day this week.

**Comment by caranicas** [comment]
got a [PR](https://github.com/photoshelter/generator-polymer-init-element-scaffold/pull/49) ready.  I want to bang on it a bit more before I merge but if you want to take a look you can pull it and use a local npm link to test.

**Comment by oneezy** [comment]
Awesome! I'll give it a go here in a bit. Trying to wrap up a little bit of stuff before I can switch gears myself 😁

**Comment by oneezy** [comment]
It's looking good on this end. I'm going to dive in a bit more and see what i might be able to contribute on

**Comment by caranicas** [comment]
solved with #49
