### ISSUE TITLE
.npmignore when I think I wanted .gitignore, though maybe I need both.

### ISSUE THREAD

**Issue by Westbrook** [photoshelter/generator-polymer-init-element-scaffold#6]
Just created three components, which was really easy, but when I went to add them to a git repo the .gitignore file was missing. It seems to be in the template, which I thought would mean it would be included by default.

## Expected Outcome
A generated element comes with the appropriate default .gitignore registry.

## Actual Outcome
Generated element came with a .npmignore, which I'm not 100% sure where came from and no .gitignore which made it want to commit x00MB of NPM and Bower components to my repo.

**Comment by caranicas** [comment]
I'll take a look, were the other dot files there, like`.travis.yml` ? There is a function specifically for moving over hidden files.

**Comment by caranicas** [comment]
fixed now, for (reference)[https://github.com/npm/npm/issues/7252]
